# Generated by Django 6.0.2 on 2026-02-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_serializer',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player_serializer',
            name='jersy_number',
            field=models.IntegerField(),
        ),
    ]
